### ISSUE TITLE
 Smart Management Workshop fails to deploy due to python version issue impacting control node (and cluster nodes)

### ISSUE THREAD

**Issue by benblasco** [redhat-partner-tech/partner-tech-days-march2021#10]
Paging @heatmiser 

**Problem:**

Cannot deploy workshop due to conflicting python dependency in config of ansible on control node.

**Where the problem occurs:**
TASK [control_node : install ansible development branch to venv] ********************************************************

**Error message:**

ERROR: Package 'ansible-core' requires a different Python: 3.6.8 not in '>=3.8'

**Possible causes:**

The role tries to pip install "      - git+https://github.com/ansible/ansible.git@devel" which may have moved forward since this last workshop was deployed.

**Logs:**

[smrtmgmt01-student1-ansible-1_mgmtlab-deploy-2021-10-25.1454.log](https://github.com/redhat-partner-tech/partner-tech-days-march2021/files/7409338/smrtmgmt01-student1-ansible-1_mgmtlab-deploy-2021-10-25.1454.log)

**Other notes**
I'll investigate if tweaking the role not to use the devel branch changes the behaviour and output.

**Comment by benblasco** [comment]
**Possible work-around/fix**

The following code change appears to have helped me get past the issue for now:

```
[bblasco@bblasco-t490s ansible-workshops]$ git diff provisioner/roles/control_node/tasks/venv.yml
diff --git a/provisioner/roles/control_node/tasks/venv.yml b/provisioner/roles/control_node/tasks/venv.yml
index 9b12c87..1f28f13 100644
--- a/provisioner/roles/control_node/tasks/venv.yml
+++ b/provisioner/roles/control_node/tasks/venv.yml
@@ -28,7 +28,8 @@
 - name: install ansible development branch to venv
   pip:
     name:
-      - git+https://github.com/ansible/ansible.git@devel
+      #- git+https://github.com/ansible/ansible.git@devel
+      - git+https://github.com/ansible/ansible.git@stable-2.10
       - psutil
       - paramiko
       - ncclient
[bblasco@bblasco-t490s ansible-workshops]$ 
```

**Comment by benblasco** [comment]
I have not experienced this issue again when deploying via a Fedora 35 container deployed on a Fedora 35 host.  I can't even find this file at all any more.  Do you suggest we close this issue @heatmiser ?

**Comment by heatmiser** [comment]
I have not experienced this either, @benblasco ...I'll leave it up to you if you want to close.  You could always open a new issue if it resurfaces again.

**Comment by benblasco** [comment]
Looks clean with AAP2 workshop code.  Happy to close
