### ISSUE TITLE
Smart Management Workshop fails to deploy due to move of ec2_instance plugin from community.aws to amazon.aws collection

### ISSUE THREAD

**Issue by benblasco** [redhat-partner-tech/partner-tech-days-march2021#9]
Paging @heatmiser 

**Problem:** 

Workshop fails to deploy due to numerous references to the following module/plugin which cannot be found:

community.aws.ec2_instance

**Root cause:** 

This module has been moved to the amazon.aws collection:

https://github.com/ansible-collections/community.aws/pull/579

**Work-around:**

Force the deployer to use community.aws collection version 1.5, like by replacing the following line in provisioner/roles/workshop_check_setup/defaults/main.yml:

```
[bblasco@bblasco-t490s ansible-workshops]$ git diff provisioner/roles/workshop_check_setup/defaults/main.yml
diff --git a/provisioner/roles/workshop_check_setup/defaults/main.yml b/provisioner/roles/workshop_check_setup/defaults/main.yml
index 51e247a..3348c5a 100644
--- a/provisioner/roles/workshop_check_setup/defaults/main.yml
+++ b/provisioner/roles/workshop_check_setup/defaults/main.yml
@@ -5,7 +5,7 @@ collections:
   - ansible.product_demos
   - redhat_cop.tower_utilities:==0.3.2
   - redhat_cop.tower_configuration:==1.0.2
-  - community.aws
+  - community.aws:==1.5.0
 
 collections_too:
   - awx.awx:==19.2.0
```

**Permanent solution:**
Change the deployer to also include the amazon.aws collection, and replace references to community.aws.ec2_instance with amazon.aws.ec2_instance

**Other notes:**
This change also impacts the ec2_instance_info module

**Logs**

[aws_collection_mgmtlab-deploy-2021-10-25.1159.log](https://github.com/redhat-partner-tech/partner-tech-days-march2021/files/7409217/aws_collection_mgmtlab-deploy-2021-10-25.1159.log)

**Comment by heatmiser** [comment]
@benblasco Is this still an issue?

**Comment by benblasco** [comment]
No, it's all good with the current instructions on the AAP2 branch.  However we may need to update the instructions to make sure folks know to use the AAP2 branch
